<br><br>
# NUMPY

In [46]:
import numpy as np
arr = np.array([[23,65,23,0],[-87,48,0,79],[0,69,-13,19]])
arr

array([[ 23,  65,  23,   0],
       [-87,  48,   0,  79],
       [  0,  69, -13,  19]])

<br><br>
### 1) MEAN

In [47]:
# mean() will return mean of given data-array by flattening it
np.mean(arr)

# within mean() we can specify axis of which we want mean of specifically
np.mean(arr, axis=1)

array([27.75, 10.  , 18.75])

<br><br>
### 2) MEDIAN

In [48]:
# median() will return median of given data-array by flattening it
np.median(arr)

# within median() we can specify axis of which we want median of specifically
np.median(arr, axis=0)

array([ 0., 65.,  0., 19.])

<br><br>
### 3) COUNT NON_ZERO

In [49]:
# count_nonzero() will return no. of non-zeroS in data-array by flattening it
np.count_nonzero(arr)

9

<br><br>
### 4) SQUEEZE

In [50]:
# squeeze() will remove extra dimension

# here we've tried to create three dimensional array which only have one 2-dimesional array in it, so with help of squeeze() we will remove that unused array
sq1array = [[[1,2,3], [4,5,6]]]
print(f"--------------- Normal array ---------------\n{sq1array}\n")
sq2array = np.squeeze(sq1array)
print(f"--------------- Squeezed array ---------------\n{sq2array}")

--------------- Normal array ---------------
[[[1, 2, 3], [4, 5, 6]]]

--------------- Squeezed array ---------------
[[1 2 3]
 [4 5 6]]


<br><br>
### 5) ARGMAX

In [51]:
# argmax() will return index of max element from the given array by flattening it
np.argmax(arr)

# NOTE : if the max number occurs multiple time, then this function will return the first iteration

7

<br><br>
### 6) ARGMIN

In [52]:
# argmin() will return index of min element from the given array by flattening it
np.argmin(arr)

# NOTE : if the min number occurs multiple time, then this function will return the first iteration

4

<br><br>
### 7) ARGWHERE

In [37]:
# argwhere() will return indices for non-zero elements from the array
np.argwhere(arr)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 3],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

<br><br>
### 8) CLIP

In [44]:
# clip() will return the array of only cliped values within the range, those are which are not within the range would be replaced by the nearest no. from the range
print(arr, "\n")
print(arr.clip(0,50))

[[23 65 23  0]
 [64 48  0 79]
 [ 0 69 42 19]] 

[[23 50 23  0]
 [50 48  0 50]
 [ 0 50 42 19]]


<br><br>
### 9) ALLCLOSE

In [67]:
# allclose() will check whether all the elements of passed two arrays are almost same or not with the tollerance given

an_arr = [[23.4, 65.6, 23.4, 0.5], [-87.4, 48.7, 0.5, 79.6], [0.4, 69.6, -13.5, 19.4]]
tollerance = 0.4

np.allclose(arr,an_arr, tollerance)

False

<br><br>
### 10) ABS

In [76]:
# abs() will return the absolute value of each element from the array


print(f"------------ Normal array ------------\n {arr}")
print(f"\n------------ Absolute array ------------\n {np.abs(arr)}")

------------ Normal array ------------
 [[ 23  65  23   0]
 [-87  48   0  79]
 [  0  69 -13  19]]

------------ Absolute array ------------
 [[23 65 23  0]
 [87 48  0 79]
 [ 0 69 13 19]]


<br><br>
# PANDAS

In [77]:
import pandas as pd

In [144]:
character_df = pd.DataFrame(
    {
        "Name" : [
            "Levi Ackerman",
            "Anne Leonhart",
            "Eren Yeager",
            "Sasha Blause",
            "Riener Braun",
            "Jean Kirstein"
            ],
        "Age" : [32, 23, 19, 20, 23, 20],
        "Sex" : ["Male", "Female", "Male", "Female", "Male", "Male"],
        "Kills" : [100, 200, 10000000000, 20, 200, 50]
    }
)

In [145]:
character_df

Name  Age     Sex        Kills
0  Levi Ackerman   32    Male          100
1  Anne Leonhart   23  Female          200
2    Eren Yeager   19    Male  10000000000
3   Sasha Blause   20  Female           20
4   Riener Braun   23    Male          200
5  Jean Kirstein   20    Male           50

<br><br>
### 1) COV

In [169]:
# cov() will return an DataFrame with the covariance of each int type column
character_df.cov(numeric_only=True)

Age         Kills
Age    2.296667e+01 -7.666667e+09
Kills -7.666667e+09  1.666667e+19

<br><br>
### 2) MEMORY_USAGE

In [156]:
# memory_usuage() will return the series of memory used by each column in DataFrame
character_df.memory_usage()

Index    128
Name      48
Age       48
Sex       48
Kills     48
dtype: int64

<br><br>
### 3) RENAME

In [92]:
# rename() will rename the name of the column for output
# rename take parameter "columns" which holds dictionary with key->value pair for (key the column name which we want to change and value with which we want to change

character_df.rename(columns = {"Name":"FullName"})

# NOTE : To actually change it in DataFrame we need to use "inplpace=True"

FullName  Age     Sex
0  Levi Ackerman   32    Male
1  Anne Leonhart   23  Female
2    Eren Yeager   19    Male
3   Sasha Blause   20  Female
4   Riener Braun   23    Male
5  Jean Kirstein   20    Male

<br><br>
### 4) SPLIT

In [95]:
# split() will expand the DataFrame by breaking specific column with specific parameter(" " -> space, in below example), and to expand we have to turn expand parameter to True

character_df[["FirstName", "LastName"]] = character_df["Name"].str.split(" ", expand=True)
character_df

Name  Age     Sex FirstName  LastName
0  Levi Ackerman   32    Male      Levi  Ackerman
1  Anne Leonhart   23  Female      Anne  Leonhart
2    Eren Yeager   19    Male      Eren    Yeager
3   Sasha Blause   20  Female     Sasha    Blause
4   Riener Braun   23    Male    Riener     Braun
5  Jean Kirstein   20    Male      Jean  Kirstein

<br><br>
### 5) REPLACE

In [108]:
# replace() will change/replace data of any specified column
character_df["FirstName"] = character_df["FirstName"].replace({"Eren":"Ereh ..."})
character_df

Name  Age     Sex FirstName  LastName
0         Levi   32    Male      Levi  Ackerman
1         Anne   23  Female      Anne  Leonhart
2  Eren Yeager   19    Male  Ereh ...    Yeager
3        Sasha   20  Female     Sasha    Blause
4       Riener   23    Male    Riener     Braun
5         Jean   20    Male      Jean  Kirstein

<br><br>
### 6) APPLY

In [122]:
# apply() will perform some given operations on specified column by passing anonymous function as an argument
character_df["FirstName"] = character_df["FirstName"].apply(lambda x : x.upper())
character_df

Name  Age     Sex FirstName  LastName
0         Levi   32    Male      LEVI  Ackerman
1         Anne   23  Female      ANNE  Leonhart
2  Eren Yeager   19    Male  EREH ...    Yeager
3        Sasha   20  Female     SASHA    Blause
4       Riener   23    Male    RIENER     Braun
5         Jean   20    Male      JEAN  Kirstein

<br><br>
### 7) APPLYMAP

In [125]:
# applymap() will perform some operation on all data-values in DataFrame by passing anonymous function as an argument
print(character_df.applymap(lambda x : type(x)))

            Name            Age            Sex      FirstName       LastName
0  <class 'str'>  <class 'int'>  <class 'str'>  <class 'str'>  <class 'str'>
1  <class 'str'>  <class 'int'>  <class 'str'>  <class 'str'>  <class 'str'>
2  <class 'str'>  <class 'int'>  <class 'str'>  <class 'str'>  <class 'str'>
3  <class 'str'>  <class 'int'>  <class 'str'>  <class 'str'>  <class 'str'>
4  <class 'str'>  <class 'int'>  <class 'str'>  <class 'str'>  <class 'str'>
5  <class 'str'>  <class 'int'>  <class 'str'>  <class 'str'>  <class 'str'>


<br><br>
### 8) QUANTILE

In [167]:
# quantile() returns the specified quantile at specified index(optional), by default it will be from 0.5 (median)
character_df.quantile(0.3, numeric_only=True)

Age      20.0
Kills    75.0
Name: 0.3, dtype: float64

<br><br>
### 9) SAMPLE

In [183]:
# sample() will return a random n no. of sample as DataFrame, if not specified it will return only one row
character_df.sample(3)

Name  Age     Sex        Kills
0  Levi Ackerman   32    Male          100
1  Anne Leonhart   23  Female          200
2    Eren Yeager   19    Male  10000000000

<br><br>
### 10) SKEW

In [187]:
# skew() will return Series with skewsness of each integer column
character_df.skew(numeric_only=True)

Age      1.821963
Kills    2.449490
dtype: float64