In [ ]:
# numpy's core is at 'ndarray' object which is used to create array.

# numpy's array unlike python list can't have heterogenous data, they only contain homogenous data.

# numpy's array have fix size, if we exceed that length numpy will delete that array and create new array with same name but more space.

<br><br>

## IMPORTING NUMPY

In [1]:
# importing numpy with abbreviation of 'np'
import numpy as np

<br><br>

## CREATING ARRAY(s)

In [2]:
# creating array with array function
rect0 = np.array(1)                                                                                             # 0D array
rect1 = np.array([1,2,3])                                                                                       # 1D array
rect2 = np.array([[1,2,3], [4,5,6]])                                                                            # 2D array
rect3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])                                                      # 3D array

# print(rect0)
# print(rect1)
# print(rect2)
print(rect3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<br><br>

## ARRAY ATTRIBUTES AND METHODS

<br><br>

### NDIM

In [30]:
# will  give dimension of the array (no. of axis)
print(rect3.ndim)

3


<br><br>

### SHAPE

In [33]:
# will give shape of the array as tuple (length of each axis -> ((z->layers), (x->rows), (y->columns))
print(rect3.shape)

(2, 2, 3)


<br><br>

### DTYPE

In [32]:
# with dtype we can view/change data type of data
sample1array = np.array([1,2,3], dtype=complex)
print(sample1array)
print(sample1array.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128


<br><br>

### SIZE

In [31]:
# will give number of elements in array (you can also calculate it by multiplying all the axis's length)
print(rect3.size)

12


<br><br>

### ZEROS

In [34]:
# will print out array with each element as zero with m-rows and n-columns
# we have to give shape of an array to parameter as tuple
zeros_array = np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


<br><br>

### ONES

In [35]:
# will print out array with each element as one with m-rows and n-columns
# we have to give shape of an array to parameter as tuple
ones_array = np.ones((3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<br><br>

### EMPTY

In [36]:
# empty will create array of m-rows and n-columns which holds random float data, but we can change it with dtype
# we have to pass argument as tuple for the size of array
empty_array = np.empty((2,3), dtype=int)
print(empty_array)

[[0 0 0]
 [0 0 0]]


<br><br>

### ARANGE

In [37]:
# will create a range from first-number(included) upto last-number(excluded) with n-number of steps if specified else 1(default) in arguments
range_array = np.arange(10,101, 10)
print(range_array)

[ 10  20  30  40  50  60  70  80  90 100]


<br><br>

### LINESPACE

In [38]:
# it will give n-number of linearly in specified interval elements between the two numbers rather than number after each steps
linespace_array = np.linspace(1,2,10)
print(linespace_array)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


<br><br>

### ARITHMETIC OPERATIONS

In [39]:
# arithmetic operation operate on elementwise(will impact all elements of array), on performing operation new array will be created with operated value. 
 
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print(f"\na : {a}")
print(f"b : {b}")
print("-------------------")

print(f"\n{a} + 5 = {a + 5}")
print(f"{a} - 1 = {a - 1}")
print(f"{a} * 10 = {a * 10}")
print(f"{a} / 10 = {a / 10}\n")


# we can also perform arithmetic operations on two or more arrays combinly
# remember arithmetic operation can be performed only on arrays with same shape(dimensions)

print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
print(f"{a} * {b} = {a * b}")
print(f"{a} / {b} = {a / b}")


a : [10 20 30 40 50]
b : [1 2 3 4 5]
-------------------

[10 20 30 40 50] + 5 = [15 25 35 45 55]
[10 20 30 40 50] - 1 = [ 9 19 29 39 49]
[10 20 30 40 50] * 10 = [100 200 300 400 500]
[10 20 30 40 50] / 10 = [1. 2. 3. 4. 5.]

[10 20 30 40 50] + [1 2 3 4 5] = [11 22 33 44 55]
[10 20 30 40 50] - [1 2 3 4 5] = [ 9 18 27 36 45]
[10 20 30 40 50] * [1 2 3 4 5] = [ 10  40  90 160 250]
[10 20 30 40 50] / [1 2 3 4 5] = [10. 10. 10. 10. 10.]


<br><br>

### MATRIC PRODUCT

In [40]:
array_1 = np.array([[1,1],[0,1]])
array_2 = np.array([[2,0],[3,4]])

# A normal multiplication between two arrays can be done m\by multiplying each element in same axes
print(f"\n---------- Normal muliplication ----------\n {array_1 * array_2}")

# But a matrix multiplication will be done like a normal mathematics matrix multiplication
print(f"\n---------- Matrix muliplication ----------\n {array_1 @ array_2}")


---------- Normal muliplication ----------
 [[2 0]
 [0 4]]

---------- Matrix muliplication ----------
 [[5 4]
 [3 4]]


<br><br>

### UNARY FUNCTIONS

In [41]:
print(f"---------- rect2 ----------\n{rect2}\n")
print(f"Minimum value : {rect2.min()}")
print(f"Maximum value : {rect2.max()}")
print(f"Sum : {rect2.sum()}")

---------- rect2 ----------
[[1 2 3]
 [4 5 6]]

Minimum value : 1
Maximum value : 6
Sum : 21


<br><br>

### INDEXING AND SLICING

In [42]:
# for one-dimensional indexing and slicing is almost same as python's list

oned_array = np.array([1,2,3,4,5,6,7])
print("--------------- One-dimensional array ---------------\n")
print(f"one_array : {oned_array} \n")
print(f"Indexing 2nd element  : {oned_array[1]}")
print(f"Slicing from 2nd element upto end : {oned_array[1:]}")
print(f"Slicing from 2nd element upto end but in reverse : {oned_array[1::-1]}")



# for multi-dimensional indexing and slicing is done bit differently

multid_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("\n\n--------------- Multi-dimensional array ---------------\n")
print(f"multid_array : \n{multid_array} \n")
# for multi-dimen indexing we have to pass index of element in multi-dimen array as tuple (r -> row no., c -> column no.)
print(f"Indexing of element at 2nd row and 3rd column : {multid_array[(1,2)]}")
print(f"Slicing element from 1st to 2nd row and 1st to 2nd column : \n{multid_array[:2, :2]}")

# NOTE : If we skip slicing for columns after coma it will be-default select all columns
# NOTE : Just like one-dimensional slicing and indexing we can also use negative indexing and slicing

--------------- One-dimensional array ---------------

one_array : [1 2 3 4 5 6 7] 

Indexing 2nd element  : 2
Slicing from 2nd element upto end : [2 3 4 5 6 7]
Slicing from 2nd element upto end but in reverse : [2 1]


--------------- Multi-dimensional array ---------------

multid_array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Indexing of element at 2nd row and 3rd column : 6
Slicing element from 1st to 2nd row and 1st to 2nd column : 
[[1 2]
 [4 5]]


<br><br>

### RESHAPE AND TRANSPOSE

In [43]:
array1 = np.array([[1,5],[3,2],[6,1],[6,3],[7,4],[9,3]])
print(f"--------------- Array ---------------\n{array1}\n")

# An array can be reshaped only in factors of its size else it will give error
print(f"--------------- Reshaped array ---------------\n{array1.reshape(1,12)}\n")

# Via transpose a new array is returned with dimensions opposite to previous one (eg. previous array's dimen -> [m,n] | new array's dimen -> [n,m])
print(f"--------------- Transposed array ---------------\n{array1.T}\n")

--------------- Array ---------------
[[1 5]
 [3 2]
 [6 1]
 [6 3]
 [7 4]
 [9 3]]

--------------- Reshaped array ---------------
[[1 5 3 2 6 1 6 3 7 4 9 3]]

--------------- Transposed array ---------------
[[1 3 6 6 7 9]
 [5 2 1 3 4 3]]



<br><br>

### STACKING ARRAYS

In [94]:
# vwhile stacking array vertically / horizontally we should confirm that array have to be of same no. of columns / no. of rows
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.array([['a','b','c'], ['d','e','f']])

print(f"\n\n--------------- Array1 ---------------\n{array1}")
print(f"\n--------------- Array2 ---------------\n{array2}")

# here array with different datatype will change type as that of superior's
print(f"\n--------------- Vertical stacking ---------------\n{np.vstack((array1, array2))}")
print(f"\n--------------- Horizontal stacking ---------------\n{np.hstack((array1, array2))}")



--------------- Array1 ---------------
[[1 2 3]
 [4 5 6]]

--------------- Array2 ---------------
[['a' 'b' 'c']
 ['d' 'e' 'f']]

--------------- Vertical stacking ---------------
[['1' '2' '3']
 ['4' '5' '6']
 ['a' 'b' 'c']
 ['d' 'e' 'f']]

--------------- Horizontal stacking ---------------
[['1' '2' '3' 'a' 'b' 'c']
 ['4' '5' '6' 'd' 'e' 'f']]


<br><br>

### SORT

In [44]:
# sort method will sort out the array
sample2array = [4,6,5,3,8]

print(f"\n--------------- Array ---------------\n{sample2array}")
print(f"\n--------------- Sorted array ---------------\n{sample2array}")


--------------- Array ---------------
[4, 6, 5, 3, 8]

--------------- Sorted array ---------------
[4, 6, 5, 3, 8]


<br><br>

### CONCATENATE

In [45]:
# concatenate will add two or more arrays in one single, though there dimensions should match
x = [1,2,3]
y = [4,5,6]
z = np.concatenate((x,y))

print(f"\n--------------- Array-x ---------------\n{x}")
print(f"\n--------------- Array-y ---------------\n{y}")
print(f"\n--------------- concatenated array of x and y ---------------\n{np.concatenate((x,y))}")


--------------- Array-x ---------------
[1, 2, 3]

--------------- Array-y ---------------
[4, 5, 6]

--------------- concatenated array of x and y ---------------
[1 2 3 4 5 6]


<br><br>

### SQUEEZE

In [46]:
# squeeze() will remove extra dimension

# here we've tried to create three dimensional array which only have one 2-dimesional array in it, so with help of squeeze() we will remove that unused array
sq1array = [[[1,2,3], [4,5,6]]]
print(f"--------------- Normal array ---------------\n{sq1array}\n")
sq2array = np.squeeze(sq1array)
print(f"--------------- Squeezed array ---------------\n{sq2array}")

--------------- Normal array ---------------
[[[1, 2, 3], [4, 5, 6]]]

--------------- Squeezed array ---------------
[[1 2 3]
 [4 5 6]]
